"""initial

Revision ID: 25fb8e95df8c
Revises: 
Create Date: 2026-03-11 13:44:25.905392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2
from geoalchemy2 import Geometry  

# revision identifiers, used by Alembic.
revision: str = '25fb8e95df8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # 2. Создание таблицы
    op.create_table('pois',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('information', sa.Text(), nullable=True),
        # Убедитесь, что здесь используется тип из GeoAlchemy2
        sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
        sa.Column('is_indoor', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.execute("DROP INDEX IF EXISTS idx_pois_geom")
    op.create_index('idx_pois_geom', 'pois', ['geom'], unique=False, postgresql_using='gist')

    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cities_country_name', 'cities', ['country_id', 'name'], unique=True)
    op.create_table('country_rules',
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('is_strict', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('country_id', 'rule_id')
    )
    op.create_table('poi_rules',
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('is_strict', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('poi_id', 'rule_id')
    )
    op.create_table('city_rules',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('is_strict', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('city_id', 'rule_id')
    )
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('purpose', postgresql.ENUM('leisure', 'business', 'education', 'other', name='trip_purpose'), nullable=False),
    sa.Column('budget', postgresql.ENUM('low', 'medium', 'high', name='budget_level'), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('other_information', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='chk_trips_dates'),
    sa.CheckConstraint('group_size >= 1', name='chk_trips_group_size'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('trip_pois',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Float(), nullable=False),
    sa.Column('planned_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('sequence_order > 0', name='chk_trip_pois_order'),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_id', 'poi_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_pois')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_table('city_rules')
    op.drop_table('poi_rules')
    op.drop_table('country_rules')
    op.drop_index('idx_cities_country_name', table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('rules')
    op.drop_index('idx_pois_geom', table_name='pois', postgresql_using='gist')
    op.drop_table('pois')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
