"""add index idx_trip_pois_trip_day on trip_pois(trip_id, day_number)

Revision ID: 3f8a9cb929e7
Revises: 74b6e9839d4e
Create Date: 2026-05-11 22:50:29.551654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8a9cb929e7'
down_revision: Union[str, Sequence[str], None] = '74b6e9839d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_trip_pois_trip_day', 'trip_pois', ['trip_id', 'day_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trip_pois_trip_day', table_name='trip_pois')
    # ### end Alembic commands ###
