"""add_ai_fields_to_trip_poi

Revision ID: 52d8b3e8ff63
Revises: 00292c896f5f
Create Date: 2026-05-11 22:27:21.692207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d8b3e8ff63'
down_revision: Union[str, Sequence[str], None] = '00292c896f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_pois', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('trip_pois', sa.Column('end_time', sa.String(), nullable=True))
    op.add_column('trip_pois', sa.Column('duration_hours', sa.Float(), nullable=True))
    op.add_column('trip_pois', sa.Column('budget_estimate', sa.String(), nullable=True))
    op.add_column('trip_pois', sa.Column('ai_tip', sa.String(), nullable=True))
    op.add_column('trip_pois', sa.Column('day_theme', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('trips', sa.Column('total_budget_estimate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'total_budget_estimate')
    op.drop_column('trips', 'ai_summary')
    op.drop_column('trip_pois', 'day_theme')
    op.drop_column('trip_pois', 'ai_tip')
    op.drop_column('trip_pois', 'budget_estimate')
    op.drop_column('trip_pois', 'duration_hours')
    op.drop_column('trip_pois', 'end_time')
    op.drop_column('trip_pois', 'start_time')
    # ### end Alembic commands ###
