"""add_day_number_to_trip_poi

Revision ID: 74b6e9839d4e
Revises: c56c8a58e7f8
Create Date: 2026-04-30 15:33:50.108059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b6e9839d4e'
down_revision: Union[str, Sequence[str], None] = 'c56c8a58e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('trip_pois', sa.Column('day_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_pois', 'day_number')

    # ### end Alembic commands ###
