"""add_city_id_to_poi

Revision ID: a28b7870f1b4
Revises: 25fb8e95df8c
Create Date: 2026-03-25 12:38:20.778858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28b7870f1b4'
down_revision: Union[str, Sequence[str], None] = '25fb8e95df8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.execute('TRUNCATE TABLE pois CASCADE')
    op.drop_index(op.f('idx_cities_country_name'), table_name='cities')
    op.create_unique_constraint('idx_cities_country_name', 'cities', ['country_id', 'name'])
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.add_column('pois', sa.Column('city_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_pois_city_id'), 'pois', ['city_id'], unique=False)
    op.create_foreign_key(None, 'pois', 'cities', ['city_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pois', type_='foreignkey')
    op.drop_index(op.f('ix_pois_city_id'), table_name='pois')
    op.drop_column('pois', 'city_id')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_constraint('idx_cities_country_name', 'cities', type_='unique')
    op.create_index(op.f('idx_cities_country_name'), 'cities', ['country_id', 'name'], unique=True)

    # ### end Alembic commands ###
